language: node_js
node_js:
  - "node"  

branches:
  only:
  - master
  
install:
- npm install -g hexo
- npm install

before_script:
- sed -i "s/__GITHUB_TOKEN__/${__GITHUB_TOKEN__}/" _config.yml

script:
- hexo generate -d

# deploy:
#   provider: pages
#   skip-cleanup: true
#   github-token: $GITHUB_TOKEN
#   keep-history: true
#   on:
#     branch: master